/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_etzwallet_core_ethereum_BREthereumBlock */

#ifndef _Included_com_etzwallet_core_ethereum_BREthereumBlock
#define _Included_com_etzwallet_core_ethereum_BREthereumBlock
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
